[package]
name = "launchpad-common"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "=1.15.4"

[dependencies.dharitri-sc-modules]
version = "=1.15.4"
